### ISSUE TITLE
Categories tidak boleh menyimpan kode yang sudah terdaftar

### ISSUE THREAD

**Issue by ridhof** [9tw/ALTA-store#25]
Penggunaan gorm unique tidak dapat mencegah data categories dengan kode yang sama, sehingga pada fungsi create perlu dilakukan pengecekan sebelum menyimpan ke dalam database.

**Comment by 9tw** [comment]
Ini di bagian post /categories ya berarti mas? @ridhof 
Di tambah validasi dulu ada atau tidak kode yg sama dengan yg ingin di insert
Bila ada yg sama maka akan keluar error
Bila tidak ada yg sama maka bisa insert

**Comment by ridhof** [comment]
betul mas di bagian post /categories 
yup flow nya begitu @9tw
