### ISSUE TITLE
Relasi antara Products dengan Categories

### ISSUE THREAD

**Issue by ridhof** [9tw/ALTA-store#30]
Relasi antara Products dengan Categories membuat beberapa perubahan

- attribute kategori_id pada Products menjadi menggunakan gorm.Models relation (jika memungkinkan)
- adanya pengecekan pada proses penambahan data products baru untuk mengecek apakah data kategori yang diberikan tersimpan di database? return error jika tidak ditemukan.

**Comment by 9tw** [comment]
Ini di bagian post /products ya? @ridhof 
Validasi ke categories ada atau tidak nya kode yg ingin dimasukan
Bila ada categories nya maka products bisa insert
Bila tidak ada categories nya maka keluar error

**Comment by ridhof** [comment]
betul mas untuk MVP kita pakai cara begitu dulu saja @9tw

**Comment by ridhof** [comment]
off dulu ya mas @9tw
