### ISSUE TITLE
Tambahkan Users pada Group JWT

### ISSUE THREAD

**Issue by ridhof** [9tw/ALTA-store#33]
- Tambahkan Users pada Group JWT
- Tidak perlu menambahkan "/jwt" pada Group JWT*

*perlu riset

**Comment by 9tw** [comment]
Sudah di coba
Hanya menghapus "/jwt" tapi routes tetap di dalam group tetap ter-cover oleh JWT

**Comment by 9tw** [comment]
Routes users yang mana yang di tambahkan ke dalam group JWT mas? @ridhof

**Comment by ridhof** [comment]
yang ini mas dipindahkan ke dalam JWT
```go
e.GET("/users", controllers.GetUsersController)
e.GET("/users/:id", controllers.GetUserController)
```
sesuai desain yang di API design @9tw
