### ISSUE TITLE
Products dan Categories controllers mengembalikan interface users 

### ISSUE THREAD

**Issue by ridhof** [9tw/ALTA-store#34]
Pada Products dan Categories saat ini mengembalikan format JSON seperti berikut ketika berhasi :

```go
func GetProductControllers(c echo.Context) error {
	id := c.Param("id")
	prods, e := database.GetProduct(id)

	if e != nil {
		return echo.NewHTTPError(http.StatusBadRequest, e.Error())
	}
	return c.JSON(http.StatusOK, map[string]interface{}{
		"status": "success",
		"users":  prods,
	})
}
```
untuk membuat JSON lebih mudah dibaca oleh developer, perlu memberikan penamaan yang sesuai yakni products pada controller products dan categories pada controller categories. Sehingga developer tidak kebingungan saat melihat JSON yang memiliki nama users tetapi memiliki nilai products/categories.

**Comment by 9tw** [comment]
Sudah saya perbaiki tapi belum di commit lanjut dulu ke enhancement berikutnya
